version: '3'
services:
        nginx:
                container_name: nginx
                image: nginx:latest
                ports:
                        - "80:80"
                volumes:
                        - "$PWD/nginx_home/nginx.conf:/etc/nginx/nginx.conf"
                        - "$PWD/templates:/etc/nginx/templates"
                networks:
                        - net

networks:
        net:

